const ChatActionsType = {
  SEND_MESSAGE_START: 'SEND_MESSAGE_START',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  RECEIVE_MESSAGES_START: 'RECEIVE_MESSAGES_START',
  RECEIVE_MESSAGES_SUCCESS: 'RECEIVE_MESSAGES_SUCCESS',
  RECEIVE_MESSAGES_FAILURE: 'RECEIVE_MESSAGES_FAILURE',
};

export default ChatActionsType;
